#test execution script.

language: scala
scala:
  - 2.10.6
  - 2.11.7
jdk:
  - oraclejdk8
sudo: false
before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -type f -delete
cache:
  directories:
    - $HOME/.sbt/0.13
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/cache
    - $HOME/.sbt/launchers
    - $HOME/.ivy2
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test:compile coverage test
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
  - sbt ++$TRAVIS_SCALA_VERSION codacyCoverage
  - sbt ++$TRAVIS_SCALA_VERSION updateImpactSubmit
  - bash <(curl -s https://codecov.io/bash)
