#test execution script.

language: scala
scala:
  - 2.10.6
  - 2.11.7
jdk:
  - oraclejdk8
sudo: false
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -type f -delete
cache:
  directories:
    - $HOME/.sbt/0.13
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/cache
    - $HOME/.sbt/launchers
    - $HOME/.ivy2
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test:compile
  - sbt ++$TRAVIS_SCALA_VERSION coverage test
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coveralls
  - sbt ++$TRAVIS_SCALA_VERSION codacyCoverage
  - sbt ++$TRAVIS_SCALA_VERSION updateImpactSubmit
