#test execution script.

language: scala
scala:
  - 2.10.5
  - 2.11.7
jdk:
  - oraclejdk8
sudo: false
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coveralls
